# Generated by Django 5.0 on 2023-12-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
